# RDS Clean Databases
Gabriel Ferreira

In [1]:
from pyspark.sql import SparkSession
from pyspark.sql.functions import *
from pyspark.sql.types import *
import psycopg2
import pandas as pd
import os
from dotenv import load_dotenv

In [2]:
# ============================================================
# LOAD ENV
# ============================================================

load_dotenv("/home/jovyan/work/.env")

RDS_HOST = os.getenv("RDS_HOST")
RDS_PORT = os.getenv("RDS_PORT")
RDS_DATABASE = os.getenv("RDS_DATABASE")
RDS_USER = os.getenv("RDS_USER")
RDS_PASSWORD = os.getenv("RDS_PASSWORD")

In [4]:
conn = psycopg2.connect(
    host="fraud-detection-rds.cilk4oyi2c5j.us-east-1.rds.amazonaws.com",
    port="5432",
    database="fraud_analytics",
    user="postgres",
    password="fraud-gabriel-rds-2026"
)

print("Connected successfully!")

Connected successfully!

In [5]:
# Validar fraud_predictions
query = """
SELECT COUNT(*)
FROM fraud_predictions;
"""

pd.read_sql(query, conn)

/tmp/ipykernel_4832/3482447501.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query, conn)

     count
0  1336675

In [6]:
# Sample
query = """
SELECT *
FROM fraud_predictions
ORDER BY inference_timestamp DESC
LIMIT 20;
"""

pd.read_sql(query, conn)

/tmp/ipykernel_4832/1391123273.py:9: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query, conn)

,trans_num,amt,city_pop,lat,long,merch_lat,merch_long,unix_time,transaction_hour,is_weekend,customer_age,high_amount_flag,night_transaction_flag,customer_merchant_distance,fraud_prediction,fraud_probability,inference_timestamp
0,7609599b-6c08-44df-b312-ec2692c35ab9,259.23,116990,35.648352,-81.293576,35.642961,-81.328790,1778700801,16,0,18,0,0,0.035624,0,0.001331,2026-05-13 20:03:14.972671
1,fec3c38b-2b3d-487c-978b-67f5c1b382a2,299.77,974783,35.336268,-89.218425,35.321683,-89.263368,1778666940,7,0,76,0,0,0.047250,0,0.007467,2026-05-13 20:03:14.972671
2,fb02a824-3d31-4f18-9fcd-991881eb8a3f,263.33,284320,30.892875,-94.582859,30.905323,-94.578914,1778622332,18,0,36,0,0,0.013058,0,0.001603,2026-05-13 20:03:14.972671
3,fb93b2d2-3049-4d9f-b572-316808b81436,128.82,4547,36.286214,-82.499280,36.242350,-82.503554,1778650872,2,0,71,0,1,0.044072,0,0.001622,2026-05-13 20:03:14.972671
4,fdda06f0-ce4f-42cb-9421-93e5c4755f29,71.92,771750,37.642593,-86.040738,37.672605,-86.069031,1778667080,7,0,23,0,0,0.041246,0,0.000288,2026-05-13 20:03:14.972671
5,8a35cf20-a5c1-4426-bf03-624e42af16c5,46.95,45288,36.236825,-85.231244,36.257197,-85.201960,1778628594,20,0,64,0,0,0.035673,0,0.000331,2026-05-13 20:03:14.972671
6,fad57f5e-dace-483c-81e1-b763509bbaa1,31.99,244816,39.944753,-78.655733,39.922838,-78.606837,1778637153,22,0,51,0,0,0.053583,0,0.002965,2026-05-13 20:03:14.972671
7,89c64bb8-0d0d-4698-9999-82de9fb1704b,155.55,649728,37.797859,-74.447809,37.810607,-74.491782,1778651092,2,0,33,0,1,0.045784,0,0.001453,2026-05-13 20:03:14.972671
8,fb57cbc8-80cb-4d6e-94e3-6b97f7eea563,119.42,561041,34.191304,-76.696008,34.197400,-76.723568,1778661299,5,0,67,0,1,0.028226,0,0.000241,2026-05-13 20:03:14.972671
9,89d0244b-a0fe-4b28-b743-e1ec2e2b1398,18.81,907825,30.574312,-84.313331,30.594959,-84.289883,1778651358,2,0,68,0,1,0.031243,0,0.009733,2026-05-13 20:03:14.972671
10,fdd90fdc-e49c-4e3e-bf29-ba40da556904,14.45,290493,40.064979,-75.048810,40.067751,-75.021641,1778696588,15,0,50,0,0,0.027310,0,0.000712,2026-05-13 20:03:14.972671
11,89e3144b-c6c6-47cb-8799-6bef557b87a7,169.59,83101,43.926625,-97.350718,43.917886,-97.342984,1778669219,7,0,26,0,0,0.011670,0,0.000278,2026-05-13 20:03:14.972671
12,767b3e12-a353-459c-9263-204bdc95b6f2,260.20,204660,43.718946,-70.573129,43.745951,-70.527494,1778622367,18,0,56,0,0,0.053027,0,0.006339,2026-05-13 20:03:14.972671
13,fe9a4eb4-a41c-433f-ac7b-d4f422fd3a0c,234.65,885496,35.722211,-97.654133,35.747062,-97.701990,1778661179,5,0,18,0,1,0.053925,0,0.000627,2026-05-13 20:03:14.972671
14,fa226819-4199-4839-997f-5e3028d73d69,123.02,140884,42.352722,-77.475048,42.368837,-77.467054,1778701759,16,0,70,0,0,0.017989,0,0.000273,2026-05-13 20:03:14.972671
15,898bf89f-da0d-4553-9d30-00be20727f41,159.68,861932,40.035188,-74.463799,40.035704,-74.470973,1778639226,23,0,61,0,0,0.007193,0,0.003771,2026-05-13 20:03:14.972671
16,75e81ad3-d58b-423f-88c1-126db20d7ed1,243.85,626001,32.316452,-95.626042,32.284732,-95.635653,1778634405,22,0,68,0,0,0.033144,0,0.024142,2026-05-13 20:03:14.972671
17,fadf1555-167a-488b-a8a4-5851760baef7,282.25,942115,39.840309,-73.937386,39.822411,-73.888471,1778683480,11,0,64,0,0,0.052087,0,0.005304,2026-05-13 20:03:14.972671
18,7605c866-3a67-40d2-8cd4-d55e1ac654b2,5707.97,43414,33.711810,-88.488998,52.565627,-78.041725,1778648450,2,0,41,1,1,21.554859,1,1.000000,2026-05-13 20:03:14.972671
19,7689cf1a-eb34-488f-a80f-515eba2fea38,265.96,697175,33.917478,-93.355770,33.887701,-93.327198,1778686778,12,0,48,0,0,0.041268,0,0.002459,2026-05-13 20:03:14.972671

In [7]:
conn.close()

print("Connection closed successfully!")

Connection closed successfully!